```{r setup}
#| include: false
library(tidyverse)
library(terra)
```

# Bias {.unnumbered}

## Precipitation

### CI

```{r prcicmip6}
#| message: false
cmip6 <- rast("results/evaluation/bias/C么te-d'Ivoire_CMIP6_chirps.nc")[[1:12]] %>% 
  median()
ggplot() +
  tidyterra::geom_spatraster(data = cmip6) +
  theme_bw() +
  theme(panel.border = element_blank(), panel.grid = element_blank(),
          panel.background = element_rect(fill = "black")) +
  ggtitle("CMIP6 vs CHIRPS", "Median across month") +
  scale_fill_gradient2("", low = "#543005", mid = "white", 
                       high = "#003c30", midpoint = 0, na.value = "black",
                       limits = c(-100, 100))
```

```{r prcicordex}
#| message: false
cordex <- rast("results/evaluation/bias/C么te-d'Ivoire_CORDEX_chirps.nc")[[1:12]] %>% 
  median()
ggplot() +
  tidyterra::geom_spatraster(data = cordex) +
  theme_bw() +
  theme(panel.border = element_blank(), panel.grid = element_blank(),
          panel.background = element_rect(fill = "black")) +
  ggtitle("CORDEX vs CHIRPS", "Median across month") +
  scale_fill_gradient2("", low = "#543005", mid = "white",
                       high = "#003c30", midpoint = 0, na.value = "black",
                       limits = c(-100, 100))
```

```{r prcidiff}
#| message: false
ggplot() +
  tidyterra::geom_spatraster(data = cmip6-cordex) +
  theme_bw() +
  theme(panel.border = element_blank(), panel.grid = element_blank(),
          panel.background = element_rect(fill = "black")) +
  ggtitle("CMIP6 - CORDEX", "Bias median across month versus CHIRPS") +
  scale_fill_gradient2("", low = "#543005", mid = "white", 
                       high = "#003c30", midpoint = 0, na.value = "black",
                       limits = c(-25, 25))
```

### FG

```{r prfgcmip6}
#| message: false
cmip6 <- rast("results/evaluation/bias/French-Guiana_CMIP6_chirps.nc")[[1:12]] %>% 
  median()
ggplot() +
  tidyterra::geom_spatraster(data = cmip6) +
  theme_bw() +
  theme(panel.border = element_blank(), panel.grid = element_blank(),
          panel.background = element_rect(fill = "black")) +
  ggtitle("CMIP6 vs CHIRPS", "Median across month") +
  scale_fill_gradient2("", low = "#543005", mid = "white", 
                       high = "#003c30", midpoint = 0, na.value = "black",
                       limits = c(-100, 100))
```

```{r prfgcordex}
#| message: false
cordex <- rast("results/evaluation/bias/French-Guiana_CORDEX_chirps.nc")[[1:12]] %>% 
  median()
ggplot() +
  tidyterra::geom_spatraster(data = cordex) +
  theme_bw() +
  theme(panel.border = element_blank(), panel.grid = element_blank(),
          panel.background = element_rect(fill = "black")) +
  ggtitle("CORDEX vs CHIRPS", "Median across month") +
  scale_fill_gradient2("", low = "#543005", mid = "white", 
                       high = "#003c30", midpoint = 0, na.value = "black",
                       limits = c(-100, 100))
```

```{r prfgdiff}
#| message: false
ggplot() +
  tidyterra::geom_spatraster(data = cmip6-cordex) +
  theme_bw() +
  theme(panel.border = element_blank(), panel.grid = element_blank(),
          panel.background = element_rect(fill = "black")) +
  ggtitle("CMIP6 - CORDEX", "Bias median across month versus CHIRPS") +
  scale_fill_gradient2("", low = "#543005", mid = "white", 
                       high = "#003c30", midpoint = 0, na.value = "black",
                       limits = c(-25, 25))
```

### NC

```{r prnccmip6}
#| message: false
cmip6 <- rast("results/evaluation/bias/New-Caledonia_CMIP6_chirps.nc")[[1:12]] %>% 
  median() %>% 
  crop(c(163, 168.5, -23, -19))
ggplot() +
  tidyterra::geom_spatraster(data = cmip6) +
  theme_bw() +
  theme(panel.border = element_blank(), panel.grid = element_blank(),
          panel.background = element_rect(fill = "black")) +
  ggtitle("CMIP6 vs CHIRPS", "Median across month") +
  scale_fill_gradient2("", low = "#543005", mid = "white", 
                       high = "#003c30", midpoint = 0, na.value = "black",
                       limits = c(-200, 200))
```

```{r prnccordex}
#| message: false
cordex <- rast("results/evaluation/bias/New-Caledonia_CORDEX_chirps.nc")[[1:12]] %>% 
  median() %>% 
  crop(c(163, 168.5, -23, -19))
ggplot() +
  tidyterra::geom_spatraster(data = cordex) +
  theme_bw() +
  theme(panel.border = element_blank(), panel.grid = element_blank(),
          panel.background = element_rect(fill = "black")) +
  ggtitle("CORDEX vs CHIRPS", "Median across month") +
  scale_fill_gradient2("", low = "#543005", mid = "white", 
                       high = "#003c30", midpoint = 0, na.value = "black",
                       limits = c(-200, 200))
```

```{r prncdiff}
#| message: false
ggplot() +
  tidyterra::geom_spatraster(data = cmip6-cordex) +
  theme_bw() +
  theme(panel.border = element_blank(), panel.grid = element_blank(),
          panel.background = element_rect(fill = "black")) +
  ggtitle("CMIP6 - CORDEX", "Bias median across month versus CHIRPS") +
  scale_fill_gradient2("", low = "#543005", mid = "white", 
                       high = "#003c30", midpoint = 0, na.value = "black",
                       limits = c(-30, 30))
```

## Temperature

### CI

```{r tascicmip6}
#| message: false
cmip6 <- rast("results/evaluation/bias/C么te-d'Ivoire_CMIP6_gshtd.nc")[[1:12]] %>% 
  median()
ggplot() +
  tidyterra::geom_spatraster(data = cmip6) +
  theme_bw() +
  theme(panel.border = element_blank(), panel.grid = element_blank(),
          panel.background = element_rect(fill = "black")) +
  ggtitle("CMIP6 vs GSHTD", "Median across month") +
  scale_fill_gradient2("", low = "#053061", mid = "white", high = "#67001f", 
                       midpoint = 0, na.value = "black",
                       limits = c(-4, 4))
```

```{r tascicordex}
#| message: false
cordex <- rast("results/evaluation/bias/C么te-d'Ivoire_CORDEX_gshtd.nc")[[1:12]] %>% 
  median()
ggplot() +
  tidyterra::geom_spatraster(data = cordex) +
  theme_bw() +
  theme(panel.border = element_blank(), panel.grid = element_blank(),
          panel.background = element_rect(fill = "black")) +
  ggtitle("CORDEX vs GSHTD", "Median across month") +
  scale_fill_gradient2("", low = "#053061", mid = "white", high = "#67001f", 
                       midpoint = 0, na.value = "black",
                       limits = c(-4, 4))
```

```{r tascidiff}
#| message: false
ggplot() +
  tidyterra::geom_spatraster(data = cmip6-cordex) +
  theme_bw() +
  theme(panel.border = element_blank(), panel.grid = element_blank(),
          panel.background = element_rect(fill = "black")) +
  ggtitle("CMIP6 - CORDEX", "Bias median across month versus GSHTD") +
  scale_fill_gradient2("", low = "#053061", mid = "white", high = "#67001f", 
                       midpoint = 0, na.value = "black",
                       limits = c(-1, 1))
```

### FG

```{r tasfgcmip6}
#| message: false
cmip6 <- rast("results/evaluation/bias/French-Guiana_CMIP6_gshtd.nc")[[1:12]] %>% 
  median()
ggplot() +
  tidyterra::geom_spatraster(data = cmip6) +
  theme_bw() +
  theme(panel.border = element_blank(), panel.grid = element_blank(),
          panel.background = element_rect(fill = "black")) +
  ggtitle("CMIP6 vs GSHTD", "Median across month") +
  scale_fill_gradient2("", low = "#053061", mid = "white", high = "#67001f", 
                       midpoint = 0, na.value = "black",
                       limits = c(-4, 4))
```

```{r tasfgcordex}
#| message: false
cordex <- rast("results/evaluation/bias/French-Guiana_CORDEX_gshtd.nc")[[1:12]] %>% 
  median()
ggplot() +
  tidyterra::geom_spatraster(data = cordex) +
  theme_bw() +
  theme(panel.border = element_blank(), panel.grid = element_blank(),
          panel.background = element_rect(fill = "black")) +
  ggtitle("CORDEX vs GSHTD", "Median across month") +
  scale_fill_gradient2("", low = "#053061", mid = "white", high = "#67001f", 
                       midpoint = 0, na.value = "black",
                       limits = c(-4, 4))
```

```{r tasfgdiff}
#| message: false
ggplot() +
  tidyterra::geom_spatraster(data = cmip6-cordex) +
  theme_bw() +
  theme(panel.border = element_blank(), panel.grid = element_blank(),
          panel.background = element_rect(fill = "black")) +
  ggtitle("CMIP6 - CORDEX", "Bias median across month versus GSHTD") +
  scale_fill_gradient2("", low = "#053061", mid = "white", high = "#67001f", 
                       midpoint = 0, na.value = "black",
                       limits = c(-1, 1))
```

### NC

```{r tasnccmip6}
#| message: false
cmip6 <- rast("results/evaluation/bias/New-Caledonia_CMIP6_gshtd.nc")[[1:12]] %>% 
  median() %>% 
  crop(c(163, 168.5, -23, -19))
ggplot() +
  tidyterra::geom_spatraster(data = cmip6) +
  theme_bw() +
  theme(panel.border = element_blank(), panel.grid = element_blank(),
          panel.background = element_rect(fill = "black")) +
  ggtitle("CMIP6 vs GSHTD", "Median across month") +
  scale_fill_gradient2("", low = "#053061", mid = "white", high = "#67001f", 
                       midpoint = 0, na.value = "black",
                       limits = c(-2, 2))
```

```{r tasnccordex}
#| message: false
cordex <- rast("results/evaluation/bias/New-Caledonia_CORDEX_gshtd.nc")[[1:12]] %>% 
  median() %>% 
  crop(c(163, 168.5, -23, -19))
ggplot() +
  tidyterra::geom_spatraster(data = cordex) +
  theme_bw() +
  theme(panel.border = element_blank(), panel.grid = element_blank(),
          panel.background = element_rect(fill = "black")) +
  ggtitle("CORDEX vs GSHTD", "Median across month") +
  scale_fill_gradient2("", low = "#053061", mid = "white", high = "#67001f", 
                       midpoint = 0, na.value = "black",
                       limits = c(-2, 2))
```

```{r tasncdiff}
#| message: false
ggplot() +
  tidyterra::geom_spatraster(data = cmip6-cordex) +
  theme_bw() +
  theme(panel.border = element_blank(), panel.grid = element_blank(),
          panel.background = element_rect(fill = "black")) +
  ggtitle("CMIP6 - CORDEX", "Bias median across month versus GSHTD") +
  scale_fill_gradient2("", low = "#053061", mid = "white", high = "#67001f", 
                       midpoint = 0, na.value = "black",
                       limits = c(-0.5, 0.5))
```
