project:
  type: book
  output-dir: docs

book:
  title: "DownClim - Downscale Climate Projections"
  author: "Sylvain Schmitt"
  date: last-modified
  chapters:
    - index.qmd
    - 01_test.qmd
    - 02_evaluations.qmd
    - 03_bias.qmd
    - 04_meteofrance.qmd
    - 11_tmf.qmd
    - 21_benchmark.qmd
  appendices:
    - 97_literature.qmd
    - 98_meetings.qmd
    - 99_references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-fold: true
    number-depth: -1

editor: visual
