rule merge_bias:
    input:
      expand("results/bias/{proj}_{baseline}_{aggregation}_{period_eval}_{period_base}_{ds_method}_{base_eval}.nc",
              proj=proj_dom.id,
              baseline=config["baseline"],
              aggregation=config["aggregation"],
              period_base=config["hist_years"],
              period_eval=config["eval_years"],
              ds_method=config["ds_method"],
              base_eval=config["base_eval"])
    output:
      expand("results/evaluation/bias/{area}_{origin}_{base_eval}.nc",
              area=config["area"],
              origin=projects,
              base_eval=config["base_eval"])
    log:
      "results/logs/merge_bias.log"
    benchmark:
      "results/benchmarks/merge_bias.benchmark.txt"
    conda:
      "../envs/xarray.yml"
    params:
      area=config["area"],
      origin=projects,
      base_eval=config["base_eval"]
    script:
      "../scripts/merge_bias.py"
